# Generated by Django 3.0.6 on 2020-05-30 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonSlideMaster',
            fields=[
                ('cls', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('courseNumber', models.IntegerField(default=9)),
                ('lessonNumber', models.IntegerField(default=9)),
                ('slideNumber', models.IntegerField(default=9)),
                ('lesson', models.CharField(max_length=100)),
                ('slide', models.CharField(max_length=100)),
                ('defaultCode', models.TextField(blank=True, default=None, null=True)),
                ('htmlBody', models.TextField(blank=True, default=None, null=True)),
                ('codedSlide', models.CharField(blank=True, default=None, max_length=1)),
                ('correctAnswer', models.TextField(blank=True, default=None, null=True)),
                ('hint', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cls', models.IntegerField()),
                ('courseNumber', models.IntegerField(default=9)),
                ('lessonNumber', models.IntegerField(default=9)),
                ('slideNumber', models.IntegerField(default=9)),
                ('code', models.TextField()),
                ('completed', models.CharField(blank=True, default='F', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
