# Generated by Django 2.2.7 on 2019-12-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseLessonSlideMaster', unique=True),
        ),
    ]
