# Generated by Django 2.2.7 on 2019-12-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191224_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='cls',
            field=models.IntegerField(),
        ),
    ]
