# Generated by Django 2.2.7 on 2019-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191224_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='courseNumber',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='lessonNumber',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='slideNumber',
            field=models.IntegerField(default=9),
        ),
    ]
