# Generated by Django 2.2.7 on 2019-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191226_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='htmlBody',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
