# Generated by Django 3.0.1 on 2019-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courselessonslidemaster_htmlbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='codedSlide',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
    ]
