# Generated by Django 3.0.1 on 2020-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courselessonslidemaster_codedslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='courseNumber',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='slides',
            name='lessonNumber',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='slides',
            name='slideNumber',
            field=models.IntegerField(default=9),
        ),
    ]
