# Generated by Django 3.0.1 on 2020-01-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200103_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonslidemaster',
            name='correctAnswer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
