# Generated by Django 3.0.1 on 2020-02-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courselessonslidemaster_correctanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='completed',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
