# Generated by Django 3.0.1 on 2020-02-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
