# Generated by Django 3.0.1 on 2020-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200217_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='completed',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
    ]
