# Generated by Django 3.0.1 on 2020-04-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200408_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='completed',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
    ]
